### ISSUE TITLE
fresh install on new Win 10 machine. Missing msvcp110.dll

### ISSUE THREAD

**Issue by rwebber** [leadedge/Spout2#31] opened 2017-11-09 19:15 UTC
Hi lynn.

I'm setting up a fresh machine.
Installing Spout 2.006 opened the installer for the x64 (missed the version) c++ redistributable as expected.
However, I am unable to open the included exe's (SpoutDXmode,exe or the Demo sender + receiver)
I get a dialog saying that msvcp110.dll is missing.

Like I said, brand new machine, so perhaps useful info.
Installing 'ONLY' the C++ Redistributable for Visual Studio 2012 update 4, x86
Solved the missing file issue, and exe's open as expected.

**Comment by leadedge** [comment] 2017-11-10 03:47
Looks like I will need to install both 32bit and 64bit re-distributables. What a nuisance.

By the way if programs are compiled /MT instead of /MD, the problem goes away because the runtimes are embedded in the executables. Unfortunately some anti-virus programs, notably Qihoo 360, flag the resulting files as containing a virus.

**Comment by rwebber** [comment] 2017-11-10 04:23
Just thought the info may be helpful since a clean machine is few and far between 😉

**Comment by leadedge** [comment] 2017-11-10 04:49
Indeed. Many thanks.

**Comment by leadedge** [comment] 2017-11-18 07:49
I had mistakenly thought that the 64bit VS2012 re-distributable was required for 64bit systems but it is actually for 64bit programs.  So I have updated the installer to detect and install the VS2012 x86 re-distributable because only 32 bit programs are provided with the Spout distribution. If other programs use Spout it is up to the developers to install the required runtime package.

The download links on the Spout website have been updated to download "SpoutSetup_V2.006a.zip". 

Other updates are :
    - SpoutReceiver.exe demo program modified to open full screen
      on whatever monitor the program was started.
          Thanks to Tim Thompson - https://github.com/nosuchtim
    - SpoutReceiver2.dll
          original IDs for Isadora
          close receiver on receivetexture fail
          https://github.com/leadedge/Spout2/issues/25
           
As you say, a fresh machine is rare indeed. Testing is difficult because although "vcredist_x86.exe" has an un-install option, the un-installation does not remove the registry entries that are checked for it's presence. However, I have confirmed that absence of these registry entries is detected OK.

At least you can run the installation to find out whether it detects that the VS2012 x86 runtime has been installed. In which case it will not prompt for runtime installation.

The registry key used for checking is -

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\11.0\VC\Runtimes\x86\Installed

This should be present and have a value of 1.

**Comment by leadedge** [comment] 2020-04-25 08:04
Issue now resolved by the installation

**Closed by leadedge** 2020-04-25 08:04 UTC
