### ISSUE TITLE
How to compile examples in the sproutsdk directory

### ISSUE THREAD

**Issue by htrlq** [leadedge/Spout2#54] opened 2020-09-10 01:25 UTC
I used examples and modified part of the code. The compilation environment is vs2017. The compiler prompts "missing type specifier - assumed to be int. Note: the default int * d:\windows kits\10\include\10.0.17763.0\um\mmsyscom.h". Do you want to configure compiler selection or install reference libraries

![image](https://user-images.githubusercontent.com/17317571/92670896-95d1be80-f347-11ea-82a8-71c184c389df.png)

**Comment by leadedge** [comment] 2020-09-10 06:32
I can't say what the problem is from your description. I assume that you are using the Openframeworks examples. The solution files are now very old and I am presently working on the beta branch as replacement. If you are using Visual Studio 2017 and Openframeworks 11, try the project generator to create a new project and include the example files and the Spout SDK files in that. Alternatively you could try the examples in the beta branch.

**Comment by htrlq** [comment] 2020-09-10 08:35
clone project to local, but not find resources 'E:\wemew.extension\Spout2-beta\libs\openFrameworksCompiled\project\vs\openframeworksLib.vcxproj'

**Comment by htrlq** [comment] 2020-09-10 08:35
branch 'bata'

**Comment by leadedge** [comment] 2020-09-10 09:03
Clearly there is something missing.

Can you create an empty project with the project generator and build it? If so, the Openframeworks project will be available.

If this is successful, you should be able to exchange the demo project files,  main.cpp, ofApp.cpp and ofApp,h, add a new filter "SpoutSDK", add existing files Add > Existing Item - select all the SpoutSKD files and add them.

Then in "ofApp.h" you will need to change "#include "..\..\..\SpoutSDK\Spout.h", to the path you actually have for these files.

**Comment by htrlq** [comment] 2020-09-10 11:02
If you use an old project, you will be prompted "unknown compiler version - please run the configure tests and report the results" when compiling. Is this the reason why the project cannot be compiled

**Comment by leadedge** [comment] 2020-09-10 12:58
Are you using the Openframeworks project generator to create a new project?

**Comment by leadedge** [comment] 2020-09-11 01:27
I have not seen the "unknown compiler version" message with Visual Studio 2017. I just tested the existing project and source files from the master branch (Spout version 2.006) and it builds without this error. These are the steps for my test ..
First, is a message as below:
<a href="https://user-images.githubusercontent.com/7351229/92833561-24157580-f418-11ea-9b9c-184048d01e30.png"><img src="https://user-images.githubusercontent.com/7351229/92833561-24157580-f418-11ea-9b9c-184048d01e30.png" width="400"/></a>
Click OK to re-target ..
<a href="https://user-images.githubusercontent.com/7351229/92833978-9c7c3680-f418-11ea-9ad6-77bba78f1fb5.png"><img src="https://user-images.githubusercontent.com/7351229/92833978-9c7c3680-f418-11ea-9ad6-77bba78f1fb5.png" width="400"/></a>
I usually change to "Release" for build but "Debug" will work as well ..
<a href="https://user-images.githubusercontent.com/7351229/92834237-f0871b00-f418-11ea-88f6-4cf77d45c13b.png"><img src="https://user-images.githubusercontent.com/7351229/92834237-f0871b00-f418-11ea-88f6-4cf77d45c13b.png" width="200"/></a>
After build there may be many warnings for updated Openframeworks (for this test I used Openframeworks 10). But these do not matter ..
<a href="https://user-images.githubusercontent.com/7351229/92834625-63909180-f419-11ea-8ca5-71c56104159d.png"><img src="https://user-images.githubusercontent.com/7351229/92834625-63909180-f419-11ea-8ca5-71c56104159d.png" width="400"/></a>
The project builds and runs successfully ..
<a href="https://user-images.githubusercontent.com/7351229/92834797-9b97d480-f419-11ea-8a17-b7f8cfe9aeab.png"><img src="https://user-images.githubusercontent.com/7351229/92834797-9b97d480-f419-11ea-8a17-b7f8cfe9aeab.png" width="400"/></a>
If at the start you click Cancel instead of OK to re-target, you will see ..
<a href="https://user-images.githubusercontent.com/7351229/92836077-29c08a80-f41b-11ea-8fdb-dcaa54f94bba.png"><img src="https://user-images.githubusercontent.com/7351229/92836077-29c08a80-f41b-11ea-8fdb-dcaa54f94bba.png" width="200"/></a>
It still builds successfully for me ..
There must be something in your system that is causing this but I can't reproduce it. After you build a project there is a ".vs" folder. Erase that and try again with the project files from GitHub.
I suggested using the Openframeworks project generator because you get a project that you can test straight away. If that succeeds, you can replace the source files with the example, include a filter with the Spout SDK files, and you might find what the problem might be.

**Comment by leadedge** [comment] 2021-01-13 00:51
I will close this now. If you have ongoing problems, I suggest that you use the Openframeworks project generator to create a new project that builds OK and add the Spout code into it.

**Closed by leadedge** 2021-01-13 00:51 UTC
