### ISSUE TITLE
Spout can't handle more than a certain number of Senders

### ISSUE THREAD

**Issue by Stefano-Rascio** [leadedge/Spout2#34] opened 2018-06-11 11:45 UTC
Hi Lynn,

I tested Spout 2.006 on different machines and I found out that there is a limit related to the number of Senders that can be created before the SDK crashes.
After an extensive investigation I found out that the same limit applies in the case where Senders are created and destroyed progressively too (for instance: Sender1 created, Sender1 destroyed; Sender2 created, Sender2 destroyed; etc...).
The limit is the same in both cases and it's 156 on my machine.
In all these cases an exception is thrown inside the nvoglv64.dll because of an access violation reading location 0x000000000000000C (n.b.: this is only visible attaching the debugger to the processes). Moreover when a Receiver is created, after the limit has been reached, the following message is shown by the SDK: 
Cannot create DirectX/OpenGL interop.
CreateDX11interop - error 1
CreateInterop - error 3

I've created two Openframeworks projects ([open close senders](https://drive.google.com/file/d/19fX3KXHErivLVcNwcK9mdSYByqtVmlXW/view) and [open n senders](https://drive.google.com/file/d/1NEcsN68pvVP_0xzo8Eyk3MtCWLc_1sJn/view)) which use the ofxXmlSettings and ofxSpout2 (only used to include the SpoutSDK) add-ons, to show the problem. There is an xml file in the bin/data folder through which is possible to set:
- the amount of sender that will be created and destroyed one after another (this is the case of the first project);
- the amount of sender that will be created (this is the case of the second project).

Thanks,
Stefano

**Comment by leadedge** [comment] 2018-06-12 01:40
Thanks for your investigations Stefano.

This issue is related to the previous one where the maximum number of senders is set to 10. If a further sender is created, the shared memory of the previous sender is over-written. SpoutPanel was revised for that issue and since then I have assembled an [update installation](http://spout.zeal.co/download/SpoutSetup_V2.006b.zip) which allows the maximum number of senders to be changed in the settings program. Could you try this with your test programs?

**Comment by Stefano-Rascio** [comment] 2018-06-12 08:40
The number of senders on my machine was already set to 250 but I've never been able to reach it (even closing and opening channels progressively). I tried the updated installation too but nothing changed, I got exactly the same issue.

**Comment by leadedge** [comment] 2018-06-12 13:35
I set up a test program and I believe it is simply running out of graphics memory. DX11 reports failure to create a shared texture. DX9 does not for some reason but in any case the interop link fails. On my machine with GTX 640, for textures of 1920x1080 the maximum number of senders is 77. I can't fault create/release of senders.

**Comment by Stefano-Rascio** [comment] 2018-06-13 08:38
According to my tests it's not running out of memory, I tried creating the maximum number of senders that my machine can handle and less than 20% of the gpu memory is used, moreover even creating and destroying a sender at a time in a for loop is giving the same outcome and this shouldn't be the case where is going out of memory since that at the end of each iteration there are no senders around. 
Furthermore it doesn't seem an issue which is related to the size of a texture since that I tried textures of diverse sizes and I always get the same behaviour.

**Comment by leadedge** [comment] 2018-06-13 13:43
I am looking into it. There is definitely something strange going on. Here is what I have found so far.

There is certainly plenty of VRAM left when it fails - monitored with GPU-Z - but spoutDirectX::CreateSharedDX11Texture definitely fails with "E_OUTOFMEMORY". 

I revise the number I mentioned previously. I get 123 as the maximum if the texture size is less than or equal to 1920x1080. Any less gives the same number, but the number of senders reduces above 1920 x 1153 (122), down to 42 at 3840x2160, so it is definitely related to texture size.

I have worked more on creating/releasing senders. Each is released OK.  I have checked the resource releases and all report a refcount of zero so I assume they are indeed freed. However I can reproduce what you see. Releasing a sender does not affect the maximum achieved, so I don't know why the memory is not released. The next thing I would try is to delete the sender object, but have not had time to do it.

There is a compatibility check- spoutGLDXinterop::GLDXready() - that is called at the very start. This creates a shared texture for the test and it might fail at this point depending on the texture size. If it does it will switch to CPU texture share mode, so you have to go back into settings to restore texture share mode for the next test. Otherwise it creates an additional staging texture and the number of senders is reduced further.

The fact that spoutDirectX::CreateSharedDX11Texture definitely fails with "E_OUTOFMEMORY" is the key. 

It could be because it is a shared texture, or because previous textures are linked with the GL/DX interop, or it could be due to how the driver manages GPU memory and makes available a limited space for resources. At this stage I don't know.

There are OpenGL resources created as well,  textures and an fbo, which will consume GPU memory. Leave the "Buffer" option OFF or two pbos are also created.

I will try to isolate this but will need to make some test code and it might take a while.

**Comment by leadedge** [comment] 2020-04-25 08:08
Update has been available for some time, so closing this issue

**Closed by leadedge** 2020-04-25 08:08 UTC
