### ISSUE TITLE
where is the source code of demo program ?

### ISSUE THREAD

**Issue by avilleret** [leadedge/Spout2#35] opened 2018-08-13 09:32 UTC
I think it will be very valuable to release the source code of the Demo program since they don't rely on external framework like openFrameworks or Cinder.

Then it will be easier to debug custom application.

**Comment by leadedge** [comment] 2018-08-14 01:35
The code for the demo program is not nice and neat. It started based on a tutorial by NEHE, and has grown from there. I have not cleaned it up because it works reliably and I know what to look for. I also use it for testing. But you are welcome to the source if you contact me.

The Spout SDK itself is not dependent on Openframeworks or Cinder, so you can use a very basic OpenGL program which would be easier to start with than the demo program code which has become complex.

**Comment by avilleret** [comment] 2018-08-14 09:57
it would be nice to provide such a simple example code with sender and receiver to help people starting with Spout and to test around different configuration by looking at the code.

**Comment by leadedge** [comment] 2018-08-14 13:06
Yes I will look at this. Here is the NEHE tutorial I mentioned. It should be easy to add code such as in the Openframeworks example to make a Spout sender.

http://nehe.gamedev.net/tutorial/texture_mapping/12038/

**Comment by leadedge** [comment] 2018-08-17 02:42
Updating this. The NEHE tutorials are still there but the download links don't work and the project is fairly old now. More recent [tutorials](http://www.opengl-tutorial.org/) use a VAO and shaders which I will be moving to ultimately. But I will look at making a basic OpenGL example.

**Comment by avilleret** [comment] 2018-08-17 07:54
I took a look at Nehe tutorial before opening this issue but since download links are down and because I'm too lazy to copy and paste all parts of code I asked you for source code :-)

But yes definitely, having small code demonstrating SPout mechanism will be very valuable.

**Comment by leadedge** [comment] 2018-08-19 00:41
The NEHE tutorials are good because they are stand-alone, but the problem is that they are legacy code. The more modern OpenGL tutorials depend on other libraries such as Glew or Glad etc., so they are not much good as a simple example. I will think about some source that would plug into those tutorials. But it will be a little while until I can get the time to do it. Meanwhile let's close this one too.

**Closed by leadedge** 2018-08-19 00:41 UTC
