### ISSUE TITLE
Spout Panel does't display more that 10 Senders

### ISSUE THREAD

**Issue by Harvey3141** [leadedge/Spout2#33] opened 2018-02-28 21:26 UTC
Hi Lynn, 

I think I have found a bug where there the Spout panel app can only handle up to 10 senders. This also seems to be apparent when getting the list of available senders from the SpoutSDK. 

I've created an Openframeworks project which shows the problem. - https://goo.gl/MQVpgC it uses this Spout addon - https://github.com/ThomasMSondrup/ofxSpout2 with the latest Spout SDK version, there's a compiled version in the Bin folder. Once running press 'a' to add spout senders one at a time. If you check the Spout Panel after reaching 10+ running senders you should what I mean. 

Thanks, 
Harvey

**Comment by leadedge** [comment] 2018-02-28 23:59
Hi Harvey,

This maximum sender number problem has come up more recently with [Touchdesigner](https://www.derivative.ca/Forum/viewtopic.php?f=12&t=11327&hilit=spout). It was fixed by setting the maximum sender size with "SetMaxSenders(int maxSenders)". 

The idea is that by the time of the next Spout release, all applications should have updated to at least 2.005 where the maxSenders registry setting is used. Then the option will be included in the settings application. Meanwhile you can use SetMaxSenders in the first application that starts.

I thought you were using this already.  It might be best if I send you the latest settings dialog program by email. I tested with a Spout 2.006 installation setting the maximum number to 12 and opening 12 demo senders. Then with a receiver, SpoutPanel (Vers 2.20) shows all 12 OK. It should be possible for you to reproduce this. 

Somehow the first link goes to the addon repository. If you can post the link again I will try the executable. 

![12_senders](https://user-images.githubusercontent.com/7351229/36819850-050554be-1d3b-11e8-8b9a-e032e2a1f661.jpg)

**Comment by Harvey3141** [comment] 2018-03-01 00:39
Hi Lynn, 

I haven't seen this issue up until now as I've been explicitly creating receivers without using the Spout Panel or needing to retrieve the list of sender names. But yes the issue does seem to be the same as the TD one. 

Before running any sending/receiving apps I have been running the Utility you sent for setting Max number of senders, actually, this is only done once per installation. Our application which creates the Spout receivers also calls SetMaxSenders(30), in my test I am running this first. I then run my sending app (correct link https://goo.gl/Dz6qLA). I've just installed using the latest 2.006 install with Spout Panel 2.20 but I am still seeing the same issue. 

If you could you check whether you are seeing the same that would be helpful. 

Thanks

**Comment by Harvey3141** [comment] 2018-03-01 00:50
As a further test, I tried. 

1. A reboot
2. Running the "SpoutDXMode Utility" and setting max senders to 30
3. Opening 12 Spout senders using the SpoutSender.exe in the spout 2.006 installer
4. Opening the spout panel v.2.20

And I see the same, senders names ending 8 and 9 are missing, if you scroll up you can see sender name ending 0 and 1

![screenshot_030118_124921_am](https://user-images.githubusercontent.com/8999833/36821316-61faffb2-1cea-11e8-84b5-a8c93e5f42f9.jpg)

**Comment by leadedge** [comment] 2018-03-01 03:26
My omission not to check that all the senders were there. I found the problem. SpoutPanel uses the SpoutSenderNames class which sets the maximum sender number to 10 by default. SpoutPanel was not checking the registry entry to update this. Attached is an update. Let me know if it works for you.

[SpoutPanel.zip](https://github.com/leadedge/Spout2/files/1769685/SpoutPanel.zip)

**Comment by Harvey3141** [comment] 2018-03-01 12:27
OK, that makes sense and yes the panel list is working now, thanks.

**Comment by sheridanis** [comment] 2018-03-01 21:54
Thanks lynn much appreciated

Also +1 for bring able to set or at least view the max senders in the control app again.

**Comment by leadedge** [comment] 2018-03-02 00:30
I believe that this change will not affect any existing applications and enough time has passed that all should be up to date with 2.005 or later, so an update release is probably worth while rather than waiting for the next version.

Since you have been using this for a while, have you found this setting to be stable and cause no problems?

**Comment by leadedge** [comment] 2020-04-25 08:06
Presumably the setting has been stable.

**Closed by leadedge** 2020-04-25 08:06 UTC
