### ISSUE TITLE
flickering because receiver sometimes can't access the shared texture.

### ISSUE THREAD

**Issue by nashiro66** [leadedge/Spout2#89] opened 2023-01-04 07:21 UTC
I implemented texture sharing between opengl process. 

However, every other draw, the program can't access shared image. [Here](https://user-images.githubusercontent.com/51952552/210500053-3c08cd75-5515-4d4c-99fa-e6e10da48196.mp4) is a demo capture.
I found that [CheckTextureAccess](https://github.com/leadedge/Spout2/blob/9db0efadba16e1d884164d348f556922cfc80c50/SPOUTSDK/SpoutGL/SpoutGL.cpp#L1445) returns false  in ReadGLDXtexture func and can't GetSharedTextureData every other draw.
Source code is [here](https://github.com/nashiro66/InterprocessImageSharing).

Thank you.

**Comment by leadedge** [comment] 2023-01-04 12:23
I have built both your receiver and sender projects and they work without flicker for me. But we need to find out what the problem is. First of all, could you try -
```

bool Receiver::Connect()
{
	if (spout.ReceiveTexture(texture.GetTexId(), GL_TEXTURE_2D, false)) {
		if (spout.IsUpdated())
		{
			texture.Resize(spout.GetSenderWidth(), spout.GetSenderHeight());
		}
		if (spout.BindSharedTexture())
		{
			ShowLog();
			return true;
		}
	}
	return false;
}
```

Next, remove the mutex test and leave the texture sync to the GL/DX interop. Remove these lines -

```
	// if (frame.CheckTextureAccess(m_pSharedTexture)) {
		--- 
		--- 
		--- 
		// frame.AllowTextureAccess(m_pSharedTexture);
	// }

```

If that solves it, put the lines back in and test for a timeout in "CheckAccess" by adding the log that is commented out.

```
			case WAIT_TIMEOUT: // The time-out interval elapsed,
			SpoutLogError("CheckAccess - WAIT_TIMEOUT");
			break;
```

Is the graphics driver vertical sync setting on or off? What is the graphics hardware?

**Comment by nashiro66** [comment] 2023-01-04 16:30
I changed my code as you suggest , but it does not work.
THe graphics hardware is GeForce RTX 2070 super and vertical sync setting is on.
I had my friend(similaly GeForce hardware) try it, but it still is flickering.

Thank you.

**Comment by leadedge** [comment] 2023-01-05 00:20
I think the problem is that the OpenGL shared texture is bound and this prevents access to the Directx shared texture that it is linked to.

There is a texture used to receive to but that is never used. Try the following -

```
bool Receiver::Connect()
{
	// Unbind if connected
	if (spout.IsConnected())
		spout.UnBindSharedTexture();

	if (spout.ReceiveTexture())
	{
		if (spout.BindSharedTexture()) {
			ShowLog();
			return true;
		}
	}
	return false;
}

```

The only problem is that the texture will be inverted because it is connected to a DirectX texture. You will need to flip the vbo texture vertices in Y.

**Comment by nashiro66** [comment] 2023-01-05 15:48
This worked! Thank you.

**Comment by leadedge** [comment] 2023-01-06 00:27
That's good. Normally you would follow BindSharedTextre() with UnBindSharedTexture(), but this will work OK.

**Closed by leadedge** 2023-01-06 00:27 UTC
