### ISSUE TITLE
Spout2 receiver with D3d11

### ISSUE THREAD

**Issue by bigt1234** [leadedge/Spout2#43] opened 2019-11-08 01:40 UTC
Hello,
I want to use d3d11 to receive spout2 textures, how should I do that I did not find the relevant example. Thanks.

**Comment by bigt1234** [comment] 2019-11-08 01:59
When I used opengl to receive spout data before, I used the following interface:

virtual bool ReceiveTexture(char* Sendername, unsigned int &width, unsigned int &height, GLuint TextureID = 0, GLuint TextureTarget = 0, bool bInvert = false, GLuint HostFBO = 0) = 0;

But I don't know what interface to use when receiving spout data using d3d11。

**Comment by leadedge** [comment] 2019-11-08 02:19
In SpoutGLDXinterop.cpp you will find  -

// DX11 shared texture write and read
bool WriteTexture(ID3D11Texture2D** texture);
bool ReadTexture (ID3D11Texture2D** texture);

In the beta branch you will find more extensive examples -

https://github.com/leadedge/Spout2/tree/beta/SPOUTSDK/Examples/DX11example

You will need to use the entire Spout 2.007 beta source files and do not mix them with 2.006. The functions should all be compatible with existing 2.006 code.

For a receiver, look at Tutorial 7. There is a SpoutDX class that could be useful. The example project is a work in progress and subject to change.
.

**Comment by bigt1234** [comment] 2019-11-08 02:21
Thank you very much. Let me go look at this example

**Comment by leadedge** [comment] 2019-11-08 02:22
I will add that for DirectX 11 you only need a sub-set of the Spout SDK if OpenGL is not used at all. Only three files are necessary.

SpoutSenderNames
SpoutDirectX
SpoutFrameCount

**Comment by bigt1234** [comment] 2019-11-08 02:26
Our new project will only use d3d11 instead of opengl. 
This news is very important. Thank you. 
I guess I shouldn't include #include < spoutlibrary.h > as before.

**Comment by bigt1234** [comment] 2019-11-08 03:02
Hello，I have a new problem
I use spout2-beta/SPOUTSDK/Examples/DX11example/Binaries/tutorial04.exe as the sending side,
use spout2-beta/SPOUTSDK/Examples/DX11example/Tutorial07/tutorial07_2017.sln as the receiver.
Build environment:
vs2015
Target Platform Version 10.0.14393.0

The receiver will not receive the data：
![1573181949(1)](https://user-images.githubusercontent.com/17736428/68446125-d0923400-0216-11ea-80f5-2f9ce9235863.jpg)
But use spout2-beta/SPOUTSDK/Examples/DX11example/Binaries/tutorial07.exe is OK:
![1573182156(1)](https://user-images.githubusercontent.com/17736428/68446305-4e563f80-0217-11ea-94c3-9ee1e24054d2.jpg)

**Comment by leadedge** [comment] 2019-11-08 03:36
SpoutLibrary.h is not needed if you are not using the library. The examples use the Spout SDK source files directly.

The projects were built with VS2017. VS2015 might be OK but I have not tested it.

Further to my comments above, these were the required include files. But in fact you have to add the following files to the project and they must be from the beta branch, not from the current 2.006 master.

SpoutCommon.h
SpoutDirectX.cpp
SpoutDirectX.h
SpoutFrameCount.cpp
SpoutFrameCount.h
SpoutSenderNames.cpp
SpoutSenderNames.h
SpoutShaderMemroy.cpp
SpoutSharedMemory.cpp
SpoutUtils.cpp
SpoutUtils.h

Otherwise I really can't say what the problem might be. I suggest you try to build Tutorial04 which simply sends the backbuffer texture. You could also use the demo sender or receiver to eliminate one or the other of the projects for testing.

**Comment by bigt1234** [comment] 2019-11-08 03:45
I didn't use the 2.006 code. I downloaded beta branches and then built Tutorial07 projects directly. I haven't made any changes to the code.

**Comment by leadedge** [comment] 2019-11-08 04:09
Honestly I have no idea of what the problem is. It builds and works perfectly for me. Of course that does not explain anything but I can't fault it.

Run SpoutSettings to make sure that texture sharing is enabled and make sure the demo sender and receiver work together. Then, try Tutorial04 to find out if it has the same problem. Look at the source code to see how the revised functions work. Basically the texture you send or receive is updated using CopyResource. The rest of the code handles size changes etc.

**Comment by leadedge** [comment] 2019-11-08 04:47
I have found the problem. The beta branch has not been updated with some bug fixes.

In SpoutDirectX.cpp - OpenDX11shareHandle

Change -
// Check m_pImmediateContext for DX11
if (!pDevice || !m_pImmediateContext || !ppSharedTexture || !dxShareHandle) {

to -
if (!pDevice || !ppSharedTexture || !dxShareHandle) {

m_pImmediateContext is never created because we are using the application device.

**Comment by bigt1234** [comment] 2019-11-08 05:08
I'm sorry that I didn't reply you in time because I had lunch just now。
After the repair as you said, the data can indeed be received. Great, thank you so much!
![1573189657(1)](https://user-images.githubusercontent.com/17736428/68451204-c9742180-0228-11ea-8560-abe8731dbcd2.jpg)

**Comment by leadedge** [comment] 2019-11-08 05:18
OK good. I will update the repository and close this now.

**Comment by bigt1234** [comment] 2019-11-08 05:18
ok

**Closed by leadedge** 2019-11-08 05:18 UTC
